services:
    api:
        build:
            context: ./server
            dockerfile: Dockerfile
        image: react-flask-app-api
    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        image: react-flask-app-client
        ports:
            - "3000:80"
