services:
    api:
        build:
            context: .
            dockerfile: Dockerfile.server
        image: react-flask-app-api
    client:
        build:
            context: .
            dockerfile: Dockerfile.client
        image: react-flask-app-client
        ports:
            - "3000:80"
